### ISSUE TITLE
MSTICPy fails to import with Bokeh 3.0

### ISSUE THREAD

**Issue by ianhelle** [microsoft/msticpy#550]
Bokeh 3.0 has just been released and changes a lot of types and type names.
You will see an error like the following if you try to use MSTICPy with Bokeh 3.0.0 or later.

```python
e:\src\msticpy\msticpy\vis\timeline_common.py in <module>
     23
     24 # pylint: enable=no-name-in-module
---> 25 from bokeh.plotting import Figure, figure
     26 from pandas.api.types import is_datetime64_any_dtype
     27 from pandas.errors import OutOfBoundsDatetime

ImportError: cannot import name 'Figure' from 'bokeh.plotting' (F:\anaconda\envs\msticpy\lib\site-packages\bokeh\plotting\__init__.py)
```

We are putting out a temporary fix to limit the supported bokeh versions to <3.0.0. We will release an updated msticpy version with bokeh 3.0 support in the future.

For current MSTICPy versions the workaround is to install a version of bokeh prior to 3.0.0
```
conda install bokeh==2.4.3
```
```
pip install bokeh==2.4.3
```

**Comment by ianhelle** [comment]
PR #552 is a workaround to prevent Bokeh 3.x ad Ipywidgets 8.x being installed with msticpy.
Both need more investigation

**Comment by kmahyyg** [comment]
Today, MSTICPy works with Bokeh 3.2.0, but not the latest 3.3.1. If you meet "Bokeh JS: javascript error: e is not iterable', please downgrade your bokeh to 3.2.0 on Python side.

I know there's nothing to blame for msticpy. Just post a workaround here for anyone if he/she met the same problem.

By the way, Bokeh 3.2.0 is not compatible with msticnb, so it depends on you, which version you'd like to use. Environment differs.
